version: v1.0

locations:
  location0:
    hostname: 127.0.0.1
    port: 8080
    workdir: /workdir
  location1:
    hostname: 127.0.0.1
    port: 8081
    workdir: /workdir
  location2:
    hostname: 127.0.0.1
    port: 8082
    workdir: /workdir
  location3:
    hostname: 127.0.0.1
    port: 8083
    workdir: /workdir
  location4:
    hostname: 127.0.0.1
    port: 8084
    workdir: /workdir
  location5:
    hostname: 127.0.0.1
    port: 8085
    workdir: /workdir
  location6:
    hostname: 127.0.0.1
    port: 8086
    workdir: /workdir
  location7:
    hostname: 127.0.0.1
    port: 8087
    workdir: /workdir
  location8:
    hostname: 127.0.0.1
    port: 8088
    workdir: /workdir
  location9:
    hostname: 127.0.0.1
    port: 8089
    workdir: /workdir
  location10:
    hostname: 127.0.0.1
    port: 8090
    workdir: /workdir
  location11:
    hostname: 127.0.0.1
    port: 8091
    workdir: /workdir
  location12:
    hostname: 127.0.0.1
    port: 8092
    workdir: /workdir
  location13:
    hostname: 127.0.0.1
    port: 8093
    workdir: /workdir
  location14:
    hostname: 127.0.0.1
    port: 8094
    workdir: /workdir
  location15:
    hostname: 127.0.0.1
    port: 8095
    workdir: /workdir
  location16:
    hostname: 127.0.0.1
    port: 8096
    workdir: /workdir
  location17:
    hostname: 127.0.0.1
    port: 8097
    workdir: /workdir
  location18:
    hostname: 127.0.0.1
    port: 8098
    workdir: /workdir
  location19:
    hostname: 127.0.0.1
    port: 8099
    workdir: /workdir
  location20:
    hostname: 127.0.0.1
    port: 8100
    workdir: /workdir
  location21:
    hostname: 127.0.0.1
    port: 8101
    workdir: /workdir
  location22:
    hostname: 127.0.0.1
    port: 8102
    workdir: /workdir
  location23:
    hostname: 127.0.0.1
    port: 8103
    workdir: /workdir
  location24:
    hostname: 127.0.0.1
    port: 8104
    workdir: /workdir
  location25:
    hostname: 127.0.0.1
    port: 8105
    workdir: /workdir
  location26:
    hostname: 127.0.0.1
    port: 8106
    workdir: /workdir
  location27:
    hostname: 127.0.0.1
    port: 8107
    workdir: /workdir
  location28:
    hostname: 127.0.0.1
    port: 8108
    workdir: /workdir
  location29:
    hostname: 127.0.0.1
    port: 8109
    workdir: /workdir
  location30:
    hostname: 127.0.0.1
    port: 8110
    workdir: /workdir
  location31:
    hostname: 127.0.0.1
    port: 8111
    workdir: /workdir
  location32:
    hostname: 127.0.0.1
    port: 8112
    workdir: /workdir
  location33:
    hostname: 127.0.0.1
    port: 8113
    workdir: /workdir
  location34:
    hostname: 127.0.0.1
    port: 8114
    workdir: /workdir
  location35:
    hostname: 127.0.0.1
    port: 8115
    workdir: /workdir
  location36:
    hostname: 127.0.0.1
    port: 8116
    workdir: /workdir
  location37:
    hostname: 127.0.0.1
    port: 8117
    workdir: /workdir
  location38:
    hostname: 127.0.0.1
    port: 8118
    workdir: /workdir
  location39:
    hostname: 127.0.0.1
    port: 8119
    workdir: /workdir
  location40:
    hostname: 127.0.0.1
    port: 8120
    workdir: /workdir
  location41:
    hostname: 127.0.0.1
    port: 8121
    workdir: /workdir
  location42:
    hostname: 127.0.0.1
    port: 8122
    workdir: /workdir
  location43:
    hostname: 127.0.0.1
    port: 8123
    workdir: /workdir
  location44:
    hostname: 127.0.0.1
    port: 8124
    workdir: /workdir
  location45:
    hostname: 127.0.0.1
    port: 8125
    workdir: /workdir
  location46:
    hostname: 127.0.0.1
    port: 8126
    workdir: /workdir
  location47:
    hostname: 127.0.0.1
    port: 8127
    workdir: /workdir
  location48:
    hostname: 127.0.0.1
    port: 8128
    workdir: /workdir
  location49:
    hostname: 127.0.0.1
    port: 8129
    workdir: /workdir
  location50:
    hostname: 127.0.0.1
    port: 8130
    workdir: /workdir
  location51:
    hostname: 127.0.0.1
    port: 8131
    workdir: /workdir
  location52:
    hostname: 127.0.0.1
    port: 8132
    workdir: /workdir
  location53:
    hostname: 127.0.0.1
    port: 8133
    workdir: /workdir
  location54:
    hostname: 127.0.0.1
    port: 8134
    workdir: /workdir
  location55:
    hostname: 127.0.0.1
    port: 8135
    workdir: /workdir
  location56:
    hostname: 127.0.0.1
    port: 8136
    workdir: /workdir
  location57:
    hostname: 127.0.0.1
    port: 8137
    workdir: /workdir
  location58:
    hostname: 127.0.0.1
    port: 8138
    workdir: /workdir
  location59:
    hostname: 127.0.0.1
    port: 8139
    workdir: /workdir
  location60:
    hostname: 127.0.0.1
    port: 8140
    workdir: /workdir
  location61:
    hostname: 127.0.0.1
    port: 8141
    workdir: /workdir
  location62:
    hostname: 127.0.0.1
    port: 8142
    workdir: /workdir
  location63:
    hostname: 127.0.0.1
    port: 8143
    workdir: /workdir
  location64:
    hostname: 127.0.0.1
    port: 8144
    workdir: /workdir
  location65:
    hostname: 127.0.0.1
    port: 8145
    workdir: /workdir
  location66:
    hostname: 127.0.0.1
    port: 8146
    workdir: /workdir
  location67:
    hostname: 127.0.0.1
    port: 8147
    workdir: /workdir
  location68:
    hostname: 127.0.0.1
    port: 8148
    workdir: /workdir
  location69:
    hostname: 127.0.0.1
    port: 8149
    workdir: /workdir
  location70:
    hostname: 127.0.0.1
    port: 8150
    workdir: /workdir
  location71:
    hostname: 127.0.0.1
    port: 8151
    workdir: /workdir
  location72:
    hostname: 127.0.0.1
    port: 8152
    workdir: /workdir
  location73:
    hostname: 127.0.0.1
    port: 8153
    workdir: /workdir
  location74:
    hostname: 127.0.0.1
    port: 8154
    workdir: /workdir
  location75:
    hostname: 127.0.0.1
    port: 8155
    workdir: /workdir
  location76:
    hostname: 127.0.0.1
    port: 8156
    workdir: /workdir
  location77:
    hostname: 127.0.0.1
    port: 8157
    workdir: /workdir
  location78:
    hostname: 127.0.0.1
    port: 8158
    workdir: /workdir
  location79:
    hostname: 127.0.0.1
    port: 8159
    workdir: /workdir
  location80:
    hostname: 127.0.0.1
    port: 8160
    workdir: /workdir
  location81:
    hostname: 127.0.0.1
    port: 8161
    workdir: /workdir
  location82:
    hostname: 127.0.0.1
    port: 8162
    workdir: /workdir
  location83:
    hostname: 127.0.0.1
    port: 8163
    workdir: /workdir
  location84:
    hostname: 127.0.0.1
    port: 8164
    workdir: /workdir
  location85:
    hostname: 127.0.0.1
    port: 8165
    workdir: /workdir
  location86:
    hostname: 127.0.0.1
    port: 8166
    workdir: /workdir
  location87:
    hostname: 127.0.0.1
    port: 8167
    workdir: /workdir
  location88:
    hostname: 127.0.0.1
    port: 8168
    workdir: /workdir
  location89:
    hostname: 127.0.0.1
    port: 8169
    workdir: /workdir
  location90:
    hostname: 127.0.0.1
    port: 8170
    workdir: /workdir
  location91:
    hostname: 127.0.0.1
    port: 8171
    workdir: /workdir
  location92:
    hostname: 127.0.0.1
    port: 8172
    workdir: /workdir
  location93:
    hostname: 127.0.0.1
    port: 8173
    workdir: /workdir
  location94:
    hostname: 127.0.0.1
    port: 8174
    workdir: /workdir
  location95:
    hostname: 127.0.0.1
    port: 8175
    workdir: /workdir
  location96:
    hostname: 127.0.0.1
    port: 8176
    workdir: /workdir
  location97:
    hostname: 127.0.0.1
    port: 8177
    workdir: /workdir
  location98:
    hostname: 127.0.0.1
    port: 8178
    workdir: /workdir
  location99:
    hostname: 127.0.0.1
    port: 8179
    workdir: /workdir

dependencies:
  d1:
    type: file
    value: /data/world.txt
    