version: v1.0

locations:
  location0:
    hostname: 127.0.0.1
    port: 8080
    workdir: /workdir
  location1:
    hostname: 127.0.0.1
    port: 8081
    workdir: /workdir
  location2:
    hostname: 127.0.0.1
    port: 8082
    workdir: /workdir

dependencies:
  d1:
    type: file
    value: /data/world.txt
    